#ifndef __ERRORS_H__
#define __ERRORS_H__

#define IMAGELIB_SUCCESS 0

// Memory erros
#define IMAGELIB_MEMORY_LOCK_ERROR -51

//
#define IMAGELIB_UNSUPPORTED_FILETYPE -200
#define IMAGELIB_HDIB_NULL -201
#define IMAGELIB_LOGICAL_PALETTE_CREATION_ERROR -202
#define IMAGELIB_STRETCHDIBITS_ERROR -204

#endif